//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

namespace Assets.Scripts.Domain {
    public class Tile {
        private GameObject Plane;
        public Vector3 Position { get { return Plane.transform.position; } }

        public Tile(GameObject _c) {
            Plane = _c;
        }
    }
}