//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using AssemblyCSharp;

namespace AssemblyCSharp
{
	public class Tile
	{
		private GameObject Plano;
		public Vector3 Position{get{return Plano.transform.position;}}

		public Tile (GameObject _c)
		{
			Plano = _c;
		}
	}
}

