//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
namespace AssemblyCSharp {
    public class SideTrigger:MonoBehaviour {
        public int faceValue = 0;
        public bool quieto = false;
        public Vector3 prevPosition;
        private DieValue dieComp;

        public SideTrigger() {}

        public void OnTriggerEnter(Collider other) {
            var dieGameObject = GameObject.Find("Dice1");
            dieComp = dieGameObject.GetComponent<DieValue>();
            dieComp.currentValue = 7 - faceValue;
        }

        public void FixedUpdate() {
            var dice = GameObject.Find("Dice1");

            if (prevPosition != dice.transform.position) {
                prevPosition = dice.transform.position;
                quieto = false;
            } else if (!quieto) {
                quieto = true;
                GameSystem.Instance.MoverCono(7 - faceValue);
                //        //Debug.LogError("Quieto: " + (7 - faceValue));
            }
        }
    }
}